//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Web.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string Admin_title {
            get {
                return ResourceManager.GetString("Admin.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кошница.
        /// </summary>
        internal static string Backet_title {
            get {
                return ResourceManager.GetString("Backet.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книги.
        /// </summary>
        internal static string Books_title {
            get {
                return ResourceManager.GetString("Books.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За връзки с нас.
        /// </summary>
        internal static string Conection_title {
            get {
                return ResourceManager.GetString("Conection.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакти.
        /// </summary>
        internal static string Contacts_title {
            get {
                return ResourceManager.GetString("Contacts.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли.
        /// </summary>
        internal static string Details_title {
            get {
                return ResourceManager.GetString("Details.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начало.
        /// </summary>
        internal static string HomePage_title {
            get {
                return ResourceManager.GetString("HomePage.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта на сайта.
        /// </summary>
        internal static string Map_title {
            get {
                return ResourceManager.GetString("Map.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меню.
        /// </summary>
        internal static string Menu_title {
            get {
                return ResourceManager.GetString("Menu.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        internal static string News_title {
            get {
                return ResourceManager.GetString("News.title", resourceCulture);
            }
        }
    }
}
