USE [master]
GO

/****** Object:  Database [BooksDBSQL]    Script Date: 17.3.2016 г. 12:55:40 ******/
CREATE DATABASE [BooksDBSQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BooksDBSQL', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BooksDBSQL.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BooksDBSQL_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BooksDBSQL_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BooksDBSQL] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BooksDBSQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BooksDBSQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BooksDBSQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BooksDBSQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BooksDBSQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BooksDBSQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [BooksDBSQL] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BooksDBSQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BooksDBSQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BooksDBSQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BooksDBSQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BooksDBSQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BooksDBSQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BooksDBSQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BooksDBSQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BooksDBSQL] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BooksDBSQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BooksDBSQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BooksDBSQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BooksDBSQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BooksDBSQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BooksDBSQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BooksDBSQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BooksDBSQL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BooksDBSQL] SET  MULTI_USER 
GO

ALTER DATABASE [BooksDBSQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BooksDBSQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BooksDBSQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BooksDBSQL] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BooksDBSQL] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BooksDBSQL] SET  READ_WRITE 
GO

